@Library('corda-shared-build-pipeline-steps@5.1') _

cordaPipeline(
    dedicatedJobForSnykDelta: false,
    gitHubComments: false,
    javaVersion: '8',
    publishToMavenS3Repository: true,
    publishRepoPrefix: 'corda',
    slimBuild: true,
    snykAdditionalCommands: "--configuration-matching='^runtimeClasspath\$' -d",
    stableUnstableRepoPattern: false,
    )
