@Library('corda-shared-build-pipeline-steps@ronanb/non-standard-publishing') _

cordaPipeline(
    publishRepoPrefix: 'corda',
    javaVersion: '8',
    slimBuild: true,
    publishToMavenS3Repository: true,
    stableUnstablePattern: false
    )
