@Library('corda-shared-build-pipeline-steps@connelm/ES-858/corda-gradle-plugins-changes') _

cordaPipeline(
    dedicatedJobForSnykDelta: false,
    gitHubComments: false,
    javaVersion: '8',
    publishToMavenS3Repository: true,
    publishRepoPrefix: 'corda',
    slimBuild: true,
    snykAdditionalCommands: "--configuration-matching='^runtimeClasspath\$' -d",
    stableUnstableRepoPattern: false,
    )