package net.corda.plugins;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

public class KotlinAutoGeneratedClassTest {
    private GradleProject testProject;

    @BeforeEach
    public void setup(@TempDir Path testProjectDir) throws IOException {
        testProject = new GradleProject(testProjectDir, "kotlin-auto-generated-class").build();
    }

    @Test
    public void testKotlinAutoGeneratedClassMethod() throws IOException {
        assertEquals("public final class net.corda.example.ContainsAutoGeneratedClass extends java.lang.Object\n" +
            "  public <init>()\n" +
            "  public final void methodContainingInlinedFunction()\n" +
            "##", testProject.getApiText());
    }
}